CREATE USER paw1 WITH PASSWORD 'paw1';

CREATE DATABASE paw1 WITH ENCODING = 'UTF8'
    TEMPLATE template0;

GRANT ALL PRIVILEGES ON DATABASE paw1 TO paw1 WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON TABLE users to paw1;

GRANT ALL PRIVILEGES ON TABLE properties to paw1;

GRANT ALL PRIVILEGES ON TABLE pictures to paw1;

GRANT ALL PRIVILEGES ON TABLE users_id_seq to paw1;

GRANT ALL PRIVILEGES ON TABLE properties_id_seq to paw1;

GRANT ALL PRIVILEGES ON TABLE pictures_id_seq to paw1;


